17:12:28.151 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider
muchiniwamback
settings  ... updated
timer  ... updated
1 76
;; Starting dbprotocols.Engine {:dbgrh {:host 178.62.81.103, :port 2424, :dbname graphdb, :username root, :password rootpwd}, :dbsql {:host 127.0.0.1, :port 5984, :dbname deadsql, :username postgres, :password postgres}, :server {:host 46.101.85.64, :port 76}}
Starting HTTP Server
Started web server on http://46.101.85.64:76/
Exception in thread "main" clojure.lang.ExceptionInfo: Error in component :restapi in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start {:reason :com.stuartsierra.component/component-function-threw-exception, :function #'com.stuartsierra.component/start, :system-key :restapi, :component #muchiniwamback.restapi.restserver{:host "46.101.85.64", :port "76", :restc nil}, :system #<SystemMap>}
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at com.stuartsierra.component$try_action.invokeStatic(component.cljc:119)
	at com.stuartsierra.component$try_action.invoke(component.cljc:116)
	at com.stuartsierra.component$update_system$fn__16658.invoke(component.cljc:139)
	at clojure.lang.ArraySeq.reduce(ArraySeq.java:114)
	at clojure.core$reduce.invokeStatic(core.clj:6747)
	at clojure.core$reduce.invoke(core.clj:6730)
	at com.stuartsierra.component$update_system.invokeStatic(component.cljc:135)
	at com.stuartsierra.component$update_system.doInvoke(component.cljc:129)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at com.stuartsierra.component$start_system.invokeStatic(component.cljc:163)
	at com.stuartsierra.component$start_system.invoke(component.cljc:155)
	at com.stuartsierra.component$start_system.invokeStatic(component.cljc:161)
	at com.stuartsierra.component$start_system.invoke(component.cljc:155)
	at com.stuartsierra.component.SystemMap.start(component.cljc:178)
	at com.stuartsierra.component$fn__16607$G__16601__16609.invoke(component.cljc:5)
	at com.stuartsierra.component$fn__16607$G__16600__16612.invoke(component.cljc:5)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.alterRoot(Var.java:305)
	at clojure.core$alter_var_root.invokeStatic(core.clj:5450)
	at clojure.core$alter_var_root.doInvoke(core.clj:5445)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at muchiniwamback.core$start.invokeStatic(core.clj:80)
	at muchiniwamback.core$start.invoke(core.clj:78)
	at muchiniwamback.core$go.invokeStatic(core.clj:89)
	at muchiniwamback.core$go.invoke(core.clj:87)
	at muchiniwamback.core$_main.invokeStatic(core.clj:114)
	at muchiniwamback.core$_main.doInvoke(core.clj:108)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at muchiniwamback.core.main(Unknown Source)
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use
	at io.undertow.Undertow.start(Undertow.java:186)
	at org.projectodd.wunderboss.web.undertow.UndertowWeb.start(UndertowWeb.java:83)
	at org.projectodd.wunderboss.web.undertow.UndertowWeb.registerHandler(UndertowWeb.java:143)
	at org.projectodd.wunderboss.web.undertow.UndertowWeb.registerHandler(UndertowWeb.java:124)
	at org.projectodd.wunderboss.web.undertow.UndertowWeb.registerHandler(UndertowWeb.java:68)
	at immutant.web.internal.wunderboss$mount.invokeStatic(wunderboss.clj:79)
	at immutant.web.internal.wunderboss$mount.invoke(wunderboss.clj:56)
	at immutant.web$run.invokeStatic(web.clj:111)
	at immutant.web$run.doInvoke(web.clj:23)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at muchiniwamback.restapi.restserver.start(restapi.clj:99)
	at com.stuartsierra.component$fn__16607$G__16601__16609.invoke(component.cljc:5)
	at com.stuartsierra.component$fn__16607$G__16600__16612.invoke(component.cljc:5)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at com.stuartsierra.component$try_action.invokeStatic(component.cljc:117)
	... 31 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.Undertow.start(Undertow.java:142)
	... 49 more
